---
- name: OSPF and ACL
  hosts: routers
  gather_facts: no

  tasks:
    - name: OSPF
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              network:
                - address: 192.168.1.0
                  wildcard_bits: 0.0.0.255
                  area: 0

    - name: ACL
      cisco.ios.ios_acls:
        state: replaced
        config:
          - afi: ipv4
            acls:
              - name: FROM_WAN
                acl_type: extended
                aces:
                  - grant: permit
                    protocol_options: 
                      ip: true
                    source:
                      any: true
                    destination:
                      address: 192.168.1.0
                      wildcard_bits: 0.0.0.255
                  - grant: deny
                    protocol_options: 
                      ip: true
                    source:
                      any: true
                    destination:
                      any: true
                    log:
                      set: true
    
    - name: Apply ACL inbound
      cisco.ios.ios_acl_interfaces:
        config:
          - name: Ethernet0/3
            access_groups:
              - afi: ipv4
                acls:
                  - name: FROM_WAN
                    direction: in

    - name: Write config-run
      cisco.ios.ios_config:
        save_when: modified